### ISSUE TITLE
specify what layout is needed on source side

### ISSUE THREAD

**Issue by Finkregh** [FiloSottile/homebrew-gomod#2]
thanks for your work!

i'd like to install two projects, but cant get gomod to do the right thing:
```
brew gomod github.com/sapcc/cyclone
go: creating new go.mod: module gomod-cyclone/2020-06-17
go: github.com/sapcc/cyclone upgrade => v0.1.10
Linking /usr/local/Cellar/gomod-cyclone/2020-06-17... 0 symlinks created

brew gomod  github.com/kayrus/gof5
go: creating new go.mod: module gomod-gof5/2020-06-17
go: github.com/kayrus/gof5 upgrade => v0.0.3
Linking /usr/local/Cellar/gomod-gof5/2020-06-17... 0 symlinks created
```

i also tried this:
```
brew gomod github.com/sapcc/cyclone/tree/master/cmd/main.go
go: creating new go.mod: module gomod-main.go/2020-06-17
go get github.com/sapcc/cyclone/tree/master/cmd/main.go: module github.com/sapcc/cyclone@upgrade found (v0.1.10), but does not contain package github.com/sapcc/cyclone/tree/master/cmd/main.go
```

What should i tell the maintainer to make installation work with gomod? Or am i holding it wrong?

**Comment by FiloSottile** [comment]
Hello! Just like with `go get`, you need to specify a path to a `main` package.

For example, that would be `github.com/sapcc/cyclone/cmd` in that project. Since the directory name is `cmd`, the binary will be called `cmd` which is probably not what they intended. This again is the same behavior as `go get`. The common idiom is to put the `main` package at `.../cmd/name` like `github.com/sapcc/cyclone/cmd/cyclone`.
